/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
    id("io.micronaut.application") version "4.5.4" apply false
    id("io.micronaut.openapi") version "4.5.4" apply false
    id("io.micronaut.aot") version "4.5.4" apply false
    id("io.micronaut.test-resources") version "4.5.4" apply false
}

rootProject.name = "full-mn"
include("tests")
include("books")
include("authors")
