apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.secret.name }}
  labels:
    {{- include "books-chart.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgresql.secret.username | b64enc | quote }}
  password: {{ .Values.postgresql.secret.password | b64enc | quote }}