apiVersion: v1
kind: Service
metadata:
  name: authors
  labels:
    {{- include "books-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.authors.service.type }}
  selector:
    app: authors
  ports:
    - port: {{ .Values.authors.service.port }}
      targetPort: {{ .Values.authors.serverPort }}