apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    {{- include "books-chart.labels" . | nindent 4 }}
spec:
  clusterIP: None  # This makes it headless
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432