apiVersion: v1
kind: Service
metadata:
  name: wiremock
  labels:
    {{- include "books-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wiremock.service.type }}
  selector:
    app: wiremock
  ports:
    - port: {{ .Values.wiremock.service.port }}
      targetPort: {{ .Values.wiremock.service.targetPort }}