micronaut:
  application:
    name: books
  server:
    port: 8080
  security:
    enabled: false
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

endpoints:
  prometheus:
    sensitive: false

context-path: /

authors:
  target:
    schema: http
    host: localhost
    port: 46666